### ISSUE TITLE
Rename plugin and config params

### ISSUE THREAD

**Issue by lena-larionova** [seifchen/kong-path-allow#1]
Kong is making an effort to use inclusive language and eradicate racially-sensitive terms from our vocabulary. Can you please update the plugin name and any properties that use the term "whitelist" to a term such as "allow"? 

On the docs side, we can make any necessary parallel changes to your plugin doc on the Kong Plugin Hub (https://docs.konghq.com/hub/seifchen/kong-path-whitelist/).

Based on work done in: https://github.com/Kong/docs.konghq.com/pull/2119

**Comment by seifchen** [comment]
ok, I will do it

**Comment by seifchen** [comment]
@lena-larionova  I have finished this, do I still need to modify my plugin doc on the Kong Plugin Hub(https://docs.konghq.com/hub/seifchen/kong-path-whitelist/)

**Comment by lena-larionova** [comment]
Thanks! I'll go ahead and update it, it's fine :)

**Comment by seifchen** [comment]
@lena-larionova Thanks! I closed this issue
