### ISSUE TITLE
Broken for Kong Version 2.X.X

### ISSUE THREAD

**Issue by tomer-friedman** [seifchen/kong-path-allow#14]
The latest [commit](https://github.com/seifchen/kong-path-allow/pull/13/files) broke for Kong 2.x.x version... 

```
nginx: [error] init_by_lua error: ...al/kong/deps/luarocks/share/lua/5.1/kong/tools/utils.lua:710: error loading module 'kong.plugins.kong-path-allow.schema':
...ks/share/lua/5.1/kong/plugins/kong-path-allow/schema.lua:10: schema typedef error: definition router_paths does not exist
```

You mention it in the release notes, but should also in the main readme..

**Comment by seifchen** [comment]
Yes, I forget it ,
Would you like to provide a patch? @tomer-friedman

**Comment by seifchen** [comment]
I have add the info to the main readme.
