### ISSUE TITLE
Plugin installation problem

### ISSUE THREAD

**Issue by ritika1003** [seifchen/kong-path-allow#16]
Hello,

I'm trying to install the plugin for Kong (version 2.7.0) using the Dockerfile and I'm having problems while trying to run the container.
The container keeps on restarting and never reaches the healthy state. I have collected the logs and attaching them here.
Could you please help me with this.

`2022/11/22 11:13:43 [error] 1#0: init_by_lua error: /usr/local/share/lua/5.1/kong/tools/utils.lua:710: error loading module 'kong.plugins.kong-path-allow.schema':
...al/share/lua/5.1/kong/plugins/kong-path-allow/schema.lua:10: schema typedef error: definition router_paths does not exist
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/kong/db/schema/typedefs.lua:585: in function '__index'
	...al/share/lua/5.1/kong/plugins/kong-path-allow/schema.lua:10: in main chunk
	[C]: at 0x7ffa0f2eb9e0
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/kong/tools/utils.lua:701: in function 'load_module_if_exists'
	/usr/local/share/lua/5.1/kong/db/schema/plugin_loader.lua:234: in function 'load_subschema'
	/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:226: in function 'load_plugin'
	/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:273: in function 'load_plugin_schemas'
	/usr/local/share/lua/5.1/kong/init.lua:541: in function 'init'
	init_by_lua:3: in main chunk
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/kong/tools/utils.lua:710: in function 'load_module_if_exists'
	/usr/local/share/lua/5.1/kong/db/schema/plugin_loader.lua:234: in function 'load_subschema'
	/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:226: in function 'load_plugin'
	/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:273: in function 'load_plugin_schemas'
	/usr/local/share/lua/5.1/kong/init.lua:541: in function 'init'
	init_by_lua:3: in main chunk`

Best regards,
Ritika

**Comment by ritika1003** [comment]
Hello, 

Thank you for your reply. This is my Dockerfile, how can I specify the version of the plugin?

```
FROM kong:2.7.0
USER root
RUN git clone https://github.com/seifchen/kong-path-allow.git && cd kong-path-allow &&  luarocks make *.rockspec
RUN luarocks install kong-plugin-url-rewrite
ADD /myVolume/kong.conf /etc/kong/kong.conf
RUN apk --no-cache add curl
USER kong
```

Best regards,
Ritika

**Comment by seifchen** [comment]
you can use :"git clone -b 0.1.3 https://github.com/seifchen/kong-path-allow.git" to select the source code

**Comment by ritika1003** [comment]
Thank you for your reply! It helped alot :)
