### ISSUE TITLE
Kong version 3.2.2-alpine

### ISSUE THREAD

**Issue by ritika1003** [seifchen/kong-path-allow#18]
Hello, 
 I'm using the new image for kong and as written in the readme to chage the version of the plugin I changed it. It does not work.
The pipeline keeps on failing.

```
Dockerfile_kong:3
--------------------
   1 |     FROM kong:3.2.2-alpine
   2 |     USER root
   3 | >>> RUN git clone --branch v0.2.0 https://github.com/seifchen/kong-path-allow.git
   4 |     RUN cd kong-path-allow
   5 |     RUN luarocks make *.rockspec
--------------------
ERROR: failed to solve: process "/bin/sh -c git clone --branch v0.2.0 https://github.com/seifchen/kong-path-allow.git" did not complete successfully: exit code: 127
```

Could you please tell me what can be the problem here.

Best regads,
Ritika

**Comment by seifchen** [comment]
@ritika1003 maybe you should check you network ,and show log . I can run 
> git clone --branch v0.2.0 https://github.com/seifchen/kong-path-allow.git

this command

**Comment by seifchen** [comment]
@ritika1003 did you install git in  kong:3.2.2-alpine, If not make sure git already install or install it .

**Comment by ritika1003** [comment]
@seifchen No i did not install git in the docker container. I will install it and try to run the image.

**Comment by ritika1003** [comment]
@seifchen It works now! Thank you for your help :)
