### ISSUE TITLE
not working on root path

### ISSUE THREAD

**Issue by linuxbandit** [seifchen/kong-path-allow#5]
Hi,
I am not sure if it is intended behaviour, but here we go

Setup:
kong 2.0 db-less deployed on kubernetes with helm chart v0.8.0

Situation:
we have a gateway which has a diverse set of hosts (`api.example.com`, `internal.example.com` etc), they all are configured with some routes.

We created a specific host (`t.example.com`) which we want to use without any route, but only allow one request path.

The following will not work

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: myingress
  namespace: kong
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/override: https-only
    konghq.com/strip-path: "true"
    konghq.com/plugins: route-restriction
spec:
  rules:
  - host: t.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: myservice
          servicePort: 80
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: route-restriction
  namespace: kong
plugin: kong-path-allow
config:
  allow_paths:
    - /trace/.+
```
(i.e. it will respond `path not allowed` on `GET t.example.com/some` and for `GET t.example.com/trace`, which I want)

The following will work
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: myingress
  namespace: kong
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/override: https-only
    konghq.com/strip-path: "true"
    konghq.com/plugins: route-restriction
spec:
  rules:
  - host: t.example.com
    http:
      paths:
      - path: /go
        backend:
          serviceName: myservice
          servicePort: 80
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: route-restriction
  namespace: kong
plugin: kong-path-allow
config:
  allow_paths:
    - /trace/.+
```

(i.e. it will respond `path not allowed` on `GET t.example.com/go/some` and it will work for `GET t.example.com/go/trace`)

I do not think this was intended, but I am open to comment. Let me know also if I omitted important information.

Thank you!

**Comment by seifchen** [comment]
@linuxbandit That is my fault, try use the last version 0.1-2 again

**Comment by seifchen** [comment]
@linuxbandit If you try success, I will close this issue. thanks

**Comment by linuxbandit** [comment]
Thank you for the quick response, I will test it either today or tomorrow!

**Comment by seifchen** [comment]
It's my pleasure, Protect yourself during the epidemic.

**Comment by seifchen** [comment]
@linuxbandit If you try success, I will close this issue. thanks

**Comment by linuxbandit** [comment]
Hi! pardon for the late reply, you know - holiday period..!

I was still not able to test, but I will let you know in case something bad is up. Let's keep it closed for now and thank you again for your support!
