### ISSUE TITLE
Installing on Kong  2.4.1 fails

### ISSUE THREAD

**Issue by rlogiacco** [seifchen/kong-path-allow#9]
I'm trying to install this plugin on a dockerized Kong instance (image `kong:2.4.1-alpine`), well aware this will get lost after restarting the container.

What I've done is getting into the console as root and issuing the following commands:
```
apk add wget
luarocks install kong-path-allow
export KONG_PLUGINS=bundled,kong-path-allow
kong prepare
kong reload
```

Sadly I'm getting the follwing error upon reload:

```
[error] 1#0: init_by_lua error: /usr/local/share/lua/5.1/kong/conf_loader/init.lua:1108: attempt to index local 'file_conf' (a nil value)
stack traceback:
	/usr/local/share/lua/5.1/kong/conf_loader/init.lua:1108: in function 'fun'
	/usr/local/share/lua/5.1/pl/tablex.lua:563: in function 'pairmap'
	/usr/local/share/lua/5.1/kong/conf_loader/init.lua:1407: in function 'conf_loader'
	/usr/local/share/lua/5.1/kong/init.lua:453: in function 'init'
	init_by_lua:3: in main chunk
[notice] 1#0: signal 17 (SIGCHLD) received from 99
```

Am I doing anything wrong or did I stumble on an incompatibility issue?

**Comment by seifchen** [comment]
use db mode  or db-less mode to run kong? Maybe you can try db-less and see if there are the same errors. If you use db mode, there are many things to pay attention to.
https://docs.konghq.com/gateway-oss/2.4.x/plugin-development/access-the-datastore/
https://docs.konghq.com/hub/seifchen/kong-path-allow/

**Comment by seifchen** [comment]
may be it is your conf not define correct

**Comment by rlogiacco** [comment]
Thanks a million.
As I use the oauth2 plugin I cannot use kong in db-less mode and, as such, I do not have a conf file to check (I only have the default template in /etc/kong) which is why I enabled the plugin via the environment variable.

Apart from step 3 and 4 anything else is very close to what you suggested, so i guess my problem was related to the KONG_PLUGINS environment variable not being set on the existing process.

I solved this by starting the container with `tail -f /dev/null`, as you suggested, setting everything up and then starting kong with the correct KONG_PLUGINS env variable: getting the list of enabled plugins (`/plugins/enabled`) returns your plugin correctly

```json
{
    "enabled_plugins": [
        "tcp-log",
        "udp-log",
        "file-log",
        "http-log",
        "key-auth",
        "hmac-auth",
        "basic-auth",
        "ip-restriction",
        "request-transformer",
        "response-transformer",
        "request-size-limiting",
        "rate-limiting",
        "response-ratelimiting",
        "syslog",
        "loggly",
        "datadog",
        "ldap-auth",
        "statsd",
        "bot-detection",
        "aws-lambda",
        "request-termination",
        "azure-functions",
        "zipkin",
        "pre-function",
        "post-function",
        "prometheus",
        "proxy-cache",
        "session",
        "acme",
        "grpc-web",
        "grpc-gateway",
        "kong-path-allow",
        "jwt",
        "acl",
        "correlation-id",
        "cors",
        "oauth2"
    ]
}
```
